plugins {
    // Apply the plugin. You can find the latest version at https://github.com/neoforged/ModDevGradle/packages/2159800.
    id 'net.neoforged.moddev' version '0.1.112'
    id 'org.groovymc.modsdotgroovy' version '2.0.0-beta.29'
	id 'groovy'
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

modsDotGroovy.gather {
    projectProperty('gml_version')
}

final mcVersion = "1.${neo_version.split('\\.', 3)[0]}.${neo_version.split('\\.', 3)[1]}"

base {
    archivesName = mod_id + '-' + mcVersion
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)
neoForge {
    version = "${neo_version}"

    parchment {
        minecraftVersion = '1.21'
        mappingsVersion = '2024.06.23'
    }

    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        eatinganimation {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    implementation "org.groovymc.gml:gml:${gml_version}"
    runtimeOnly "curse.maven:farmers-delight-398521:5566383"
}
